#!/bin/sh

# Runs a command for each URL argument.
# Arguments: [URL ...]

set -e -u

for url; do
    notify-send -- 'Enclosure URL' "$url"

    # Example: (using https://github.com/mhogomchungu/media-downloader)
    flatpak run io.github.mhogomchungu.media-downloader -a -u "$url"
done
